name: polarr_env
channels:
  - conda-forge
  - ioam
dependencies:
  - python=3.6
  - numpy
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - tqdm
    - tensorflow
    - sklearn
    - pillow
    - opencv-python
    - scikit-image